name: Build and check fonts

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ">=3.8"
    - name: Install Python dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip3 install -r requirements.txt
    - name: Install other dependencies
      run: sudo apt install woff2
    - name: Build
      run: source venv/bin/activate; cd sources; ./build.sh
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        path: fonts/**
  check:
    name: Check
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ">=3.8"
    - name: Install Python Fontbakery
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip3 install shaperglot glyphsets fontbakery
    - name: Download the Artifact
      uses: actions/download-artifact@v4
    - name: Run Fontbakery
      run: |
        source venv/bin/activate
        fontbakery check-universal \
          -x opentype/STAT/ital_axis \
          -x smart_dropout \
          artifact/ttf/*.ttf
